### ISSUE TITLE
6.0.8 Fermentation Barrel getRecipe() causes server crash

### ISSUE THREAD

**Issue by SangurianSoul** [GrowthcraftCE/Growthcraft-1.16#105]
In the latest version for 1.16, we are having a severe crash with the fermentation barrel. We just updated the mod today, and anytime a player gets within render distance of a barrel, it crashes the whole server
[crash-2022-02-07_01.29.43-server.txt](https://github.com/GrowthcraftCE/Growthcraft-1.16/files/8011573/crash-2022-02-07_01.29.43-server.txt)
.

**Comment by SangurianSoul** [comment]
I should also note that we had no problem with version 6.0.7. its only when we updated that we began experiencing this huge crash and had to go back to .7

**Comment by Alatyami** [comment]
Client vs Server side strikes again. We'll prioritize this for the next release, thank you for reporting it.

**Comment by Alatyami** [comment]
Looks to be related to getRecipe(...)

```
	at growthcraft.cellar.common.tileentity.FermentBarrelTileEntity.getRecipe(FermentBarrelTileEntity.java:279) ~[growthcraft:6.0.8] {re:classloading}
```

**Comment by Ashley123477** [comment]
Any news on this?

**Comment by SangurianSoul** [comment]
Any possibility of having this fixes as a Hotfix to 1.16?

My server mates are really looking forward to everything that 6.0.8 adds...

**Comment by SangurianSoul** [comment]
I noticed the update placed here 6 days ago. Im not sure if that was meant to fix our issue, but unfortunately it did not
[crash-2022-04-05_19.48.48-server.txt](https://github.com/GrowthcraftCE/Growthcraft-1.16/files/8420702/crash-2022-04-05_19.48.48-server.txt)
.

@Alatyami 

This is a new issue, so i dont know if the Fermentation Barrel issue is fixed

**Comment by SangurianSoul** [comment]
However, i think it now has a problem with the Milk recipe
