### ISSUE TITLE
6.0.9-10 SERVER CRASH Related to Milk Recipe in Vat

### ISSUE THREAD

**Issue by SangurianSoul** [GrowthcraftCE/Growthcraft-1.16#117]
[crash-2022-04-05_19.48.48-server.txt](https://github.com/GrowthcraftCE/Growthcraft-1.16/files/8428781/crash-2022-04-05_19.48.48-server.txt)

This happens when anyone attempts to join the server. This happens with both 6.0.9 and 6.0.10

**Comment by Alatyami** [comment]
According to the log, this is an issue with the Ferment Barrel. Has been resolved via #105
