### ISSUE TITLE
No way to get Growthcraft Milk & Pancheon doesn't visually fill.

### ISSUE THREAD

**Issue by Hensikt** [GrowthcraftCE/Growthcraft-1.16#124]
In the 6.0.10 version the Pancheon doesn't accept normal Minecraft milk in the place of that milk there is Growthcraft milk but there is no (in my case) known method to get the Growthcraft milk.

If you fill the Pancheon it does work (It's instant) but visually it doesn't fill up.

If more info is needed I'm happy to provide it.

**Comment by Alatyami** [comment]
Plenty of info, thank you.
