### ISSUE TITLE
JEI breaks in multiplayer

### ISSUE THREAD

**Issue by Hensikt** [GrowthcraftCE/Growthcraft-1.16#130]
JEI and the vanilla recipe book will not show any recipes in a multiplayer game if growthcraft 6.0.10 is installed.

**Comment by Alatyami** [comment]
Our arch nemesis returns ....

**Comment by Alatyami** [comment]
Tested in 6.0.11 and couldn't repeat .... 6.0.11 will be released today to curse forge.
