### ISSUE TITLE
Server Crash when Opening Apiary 6.0.11

### ISSUE THREAD

**Issue by SangurianSoul** [GrowthcraftCE/Growthcraft-1.16#133]
Like the title

All blocks can exist happily in the server with no issues.

Opening the Bee Box crashed the whole server
[crash-2022-05-15_19.08.00-server.txt](https://github.com/GrowthcraftCE/Growthcraft-1.16/files/8695529/crash-2022-05-15_19.08.00-server.txt)
.

**Comment by Alatyami** [comment]
Fixed for 6.1.0 ... pushing out a snapshot in a couple of minutes.

**Comment by SangurianSoul** [comment]
> Fixed for 6.1.0 ... pushing out a snapshot in a couple of minutes.

Sounds great!
