### ISSUE TITLE
Server Crash when Opening Roaster 6.1

### ISSUE THREAD

**Issue by SangurianSoul** [GrowthcraftCE/Growthcraft-1.16#136]
As the title says, server crash upon opening roaster block

[crash-2022-05-16_02.18.31-server.txt](https://github.com/GrowthcraftCE/Growthcraft-1.16/files/8696366/crash-2022-05-16_02.18.31-server.txt)

**Comment by Alatyami** [comment]
Thanks! Same issue as the bee box, will fix tonight

**Comment by SangurianSoul** [comment]
No problem! Thanks!
