### ISSUE TITLE
Starter culture does not producing from skim milk

### ISSUE THREAD

**Issue by CastorF1ber** [GrowthcraftCE/Growthcraft-1.16#155]
I put skim milk into a culture jar and process has begun. When the process finish (according to progress bar), starter culture does not appear in slot

**Comment by Alatyami** [comment]
The recipe for this has changed. To get your first Starter Culture, take a Bucket of Skim Milk with a Stick in a crafting table. Once you have your first starter culture then Skim Milk + Starter Culture will start duplicating the culture in the Culture Jar.

**Comment by CastorF1ber** [comment]
Wow. Ok

**Comment by Alatyami** [comment]
Had to change due to switching to JSON recipes, the JSON didn't like Minecraft:air as an ingredient.

**Comment by CastorF1ber** [comment]
Poor air...
