### ISSUE TITLE
Pancheon picky about showing milk

### ISSUE THREAD

**Issue by Hensikt** [GrowthcraftCE/Growthcraft-1.16#156]
If you put normal minecraft milk in the pancheon (the milk you get from cows) it doesn't show in the pancheon but if you pull it out and get the Growthcraft Milk and put that in again the pancheon does show its content. 

This is on: growthcraft-6.1.0.5-SNAPSHOT

**Comment by CastorF1ber** [comment]
Regular minecraft milk shows in puncheon only when you add 2 buckets. If you put 1 bucket it does not shown

**Comment by Alatyami** [comment]
Thank you for the continued testing. Looks like the scale needs to be adjusted.
