### ISSUE TITLE
Mix vat behaviour not as intended

### ISSUE THREAD

**Issue by Ignister127** [GrowthcraftCE/Growthcraft-1.16#158]
fill the milk vat as usual with 4 buckets of milk and 1 bucket of rennet
Insert the starter culture
The culture will start to "brew" the milk without the need of a stick,wether you use one(or multiple ones as the vat seems to accept an infinite amount of sticks)
However no whey is generated, just the cultured milk.
Also, should you try to make a new batch of cultured milk with a vat that deleted its contents after using the ingredients to make a type of cheese, no cultured milk or whey will be generated. The vat will simply empty itself

**Comment by Ignister127** [comment]
Also it's worth nothing that the milk used wasn't the vanilla one but the one from the growthcraft milk mod, since the vat won't accept the stick when filled with normal milk

**Comment by CastorF1ber** [comment]
Hmm... I tried to make cultured milk and I got also whey
