### ISSUE TITLE
Bottles do not fill after clicking on barrel

### ISSUE THREAD

**Issue by CastorF1ber** [GrowthcraftCE/Growthcraft-1.16#160]
When I click on a full barrel with a bottle bottle does not fill with fluid. Bottle disappears. This bug is unstable: sometimes bottle fills with drink, but in most situations this bug occurs

**Comment by Alatyami** [comment]
We've tried to repeat this bug, but haven't been able to. Which version of the mod are you running?

**Comment by Alatyami** [comment]
6.1.0.9-SNAPSHOT has been released ... please check this version.
https://github.com/GrowthcraftCE/Growthcraft-1.16/releases/tag/6.1.0.9
