### ISSUE TITLE
I want to upload GrowthCraft to MC Chinese encyclopedia.

### ISSUE THREAD

**Issue by JiuLiYing** [GrowthcraftCE/Growthcraft-1.16#163]
It is very difficult for Chinese players to download GrowthCraft because the Chinese government prohibits access to curseforge.com and github.com. So I want to upload GrowthCraft to the MC Chinese Encyclopedia website in China. Is it allowed? The website of Chinese Encyclopedia is: www.mcmod.cn

**Comment by JiuLiYing** [comment]
This is the GrowthCraft page of Chinese Encyclopedia：https://www.mcmod.cn/class/326.html

**Comment by Alatyami** [comment]
Yes, you can republish to that site.
