### ISSUE TITLE
Visual related bugs list

### ISSUE THREAD

**Issue by Ooferine** [GrowthcraftCE/Growthcraft-1.16#167]
## Missing Textures

- [x] Cultivated Farmland and Flooded Cultivated Farmland
- [x] Iron Milking Bucket

## Held Items (right/left)
- [x] Knife, rotated 90 degrees
- [x] Rice, rotated 90 degrees
- [x] Cooked Rice, rotated 90 degrees
- [x] Rice Stalk, rotated 90 degrees
- [x] Sushi Roll, rotated 90 degrees
- [x] All Grains, positioned like shields
- [x] Culture Jar, to small

**Comment by Alatyami** [comment]
Ah, new cultivated farmland texture was missing from git.
