### ISSUE TITLE
core/server config file doesn't generate/missing

### ISSUE THREAD

**Issue by Yankas** [GrowthcraftCE/Growthcraft-1.16#169]
I was looking to disable the salt ore genand after a bit of digging, an option to disable it was supposedly added see issue #104. After a quick read through the code, if I understood it correctly, there should be a config file called growthcraft-server.toml. The module configs (rice, apiary, milk, cellar) generate just fine. 

I tried deleting all config files and running the game, this did not resolve the issue. I also tried to recreate the issue with a clean profile with just forge + growthcraft, and the issue seems to persist.

Forge: 36.2.34
Growthcraft: 6.0.11 BETA
---------------------------------------------------------------
![Screenshot 2022-06-05 192832](https://user-images.githubusercontent.com/3958914/172062775-7d4354fc-538a-4a17-98e3-129b853b48d2.png)

**Comment by Alatyami** [comment]
Thank you for submitting, I'll get it fixed in the next snapshot.
