### ISSUE TITLE
1.16.5的混合桶无法合成奶酪

### ISSUE THREAD

**Issue by 3079334890** [GrowthcraftCE/Growthcraft-1.16#197]
我使用的是forge端6.1.0正式版mod，他可以制作Rennet Bottle和Starter Culture但是他们无法用在Cheese Vat上，所以无法制作各种奶酪

**Comment by Alatyami** [comment]
Growthcraft 6.1.4 has a lot of bug fixes.

https://www.curseforge.com/minecraft/mc-mods/growthcraft-community-edition/files/4029202
