### ISSUE TITLE
Error when loading the mod on a server. Client side works just fine

### ISSUE THREAD

**Issue by ZaDaNieL02** [GrowthcraftCE/Growthcraft-1.16#59]
I don't know what the error means and what I should do. I am getting it from two mods. Growthcraft and AwesomeDungeons, but I am at least looking forward to solve the issue for Growthcraft. Thank you in advance if anyone can help.

Crash Report:

[crash-2021-11-02_14.34.14-fml.txt](https://github.com/GrowthcraftCE/Growthcraft-1.16/files/7461147/crash-2021-11-02_14.34.14-fml.txt)

**Comment by Alatyami** [comment]
This has been fixed in 6.0.6 which will be released later today. 

Duplicates #52

**Comment by ZaDaNieL02** [comment]
Oh okay. Thank you very much
