### ISSUE TITLE
Rope

### ISSUE THREAD

**Issue by Alatyami** [GrowthcraftCE/Growthcraft-1.16#8]
Rope Block used for growing Hops and Grapes. 

Rope needs to be able to clone the texture of fences and be able to connect to other rope blocks. When a rope is used to activate a fence it should replace the fence with a fence post of the same texture and a rope knot tied around it.

Growthcraft Hops and Grapes both depend on this being completed.

**Comment by Alatyami** [comment]
The rope block is fully functional. However, we are having issues getting the texture of fence block that it is wrapped around. For now, it is just a brown post.

**Comment by hron84** [comment]
What if the wrapped rope block is just a hollow model and let the original fence block pass through on it? Like, rope-logged fence.
