### ISSUE TITLE
No way of getting wine or bayanus yeast in current patch

### ISSUE THREAD

**Issue by FUEGO40** [GrowthcraftCE/Growthcraft-1.16#83]
I'm not sure if this is how bug or issue reporting works, but like the title says, I am unable of getting bayanus yeast or fermenting grape juice of any kind. When harvesting grapes I only get the grapes themselves and no bayanus yeast, the culture jars I filled with grape juice and heated with fire don't produce bayanus yeast, and when putting the grape juice in the fermenting barrel it doesn't produce wine (probably because I can't get bayanus yeast).

**Comment by Alatyami** [comment]
Bayanus yeast drops are enabled in the next release. 
Which specific version are you using?

**Comment by Alatyami** [comment]
Found a missing global loot modifier for bayanus yeast.

**Comment by Alatyami** [comment]
Making bayanus yeast in the culture jar requires that you start with one yeast, which drops from grass and no heat applied under it.
